enable = ["nvim", "nano", "quickshell"]

subconfs = ["nano.toml"]

[defs]
quickshell_dir_name = "slowshell"
quickshell_prop_a = "value123"
quickshell_enable_b = "false"

[groups.nvim]
in_path = "neovim"
out_path = "/tmp/.config/nvim"

[groups.sway]
in_path = "sway"
out_path = "/tmp/.config/sway"

[groups.waybar]
in_path = "waybar"
out_path = "/tmp/.config/waybar"
requires = ["sway"]

[groups.quickshell]
in_path = "quickshell"
out_path = "/tmp/.config/${quickshell_dir_name}"
conflicts = ["waybar"]
process = 'defsubs'
